services:
  - type: web
    name: django-medical-chatbot
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
